export const fontCatalog=[
  {id:'noto-sans',label:'Noto Sans JP（ゴシック）',file:'NotoSansJP',extension:'otf'},
  {id:'noto-serif',label:'Noto Serif JP（明朝）',file:'NotoSerifJP',extension:'otf'},
  {id:'rounded',label:'M PLUS Rounded 1c（丸ゴシック）',file:'MPLUSRounded1c',extension:'ttf'},
  {id:'biz-gothic',label:'BIZ UDPゴシック',file:'BIZUDPGothic',extension:'ttf'},
  {id:'biz-mincho',label:'BIZ UDP明朝',file:'BIZUDPMincho',extension:'ttf'},
  {id:'zen-gothic',label:'Zen角ゴシック New',file:'ZenKakuGothicNew',extension:'ttf'},
];
export const defaultFontId='noto-sans';
const loaded=new Map(),pending=new Map();
const registeredBase64=new Map();
export function base64ToBytes(value){
  if(typeof value!=='string'||!value.length)throw new Error('フォントのBase64データがありません。');
  return Uint8Array.from(atob(value),char=>char.charCodeAt(0));
}
// Registration is additive: no font payload is generated by the editor.
export function registerEmbeddedFont({id,label,regular,bold}){
  if(!/^[a-z0-9-]+$/.test(id)||fontCatalog.some(font=>font.id===id))throw new Error('フォントIDが無効または登録済みです。');
  if(!regular||!bold)throw new Error('標準・太字のBase64データを指定してください。');
  registeredBase64.set(id,{regular,bold});fontCatalog.push({id,label:label||id});
}
export function fontKey(bold=false,fontId=defaultFontId){return `${fontId}:${Boolean(bold)}`;}
export function textFontFamily(fontId=defaultFontId){return 'PDFStudio-'+fontId;}
export function ensureTextFonts(fontId=defaultFontId,bold=false) {
  const key=fontKey(bold,fontId);
  if(!pending.has(key))pending.set(key,(async()=>{
    const definition=fontCatalog.find(font=>font.id===fontId);
    if(!definition)throw new Error('選択されたフォントが見つかりません。');
    const registered=registeredBase64.get(fontId);
    const embedded=globalThis.__PDF_STUDIO_STANDALONE__?.getFontBase64;
    const base64=registered?registered[bold?'bold':'regular']:embedded?embedded(`${definition.file}-${bold?'Bold':'Regular'}`):(await import(`../vendor/fonts/${definition.file}-${bold?'Bold':'Regular'}.base64.js`)).default;
    const bytes=base64ToBytes(base64).buffer;
    const parsed=globalThis.fontkit.create(new Uint8Array(bytes));
    const face=new FontFace(textFontFamily(fontId),bytes,{weight:bold?'700':'400'});
    await face.load();document.fonts.add(face);loaded.set(key,{bytes,parsed});
  })().catch(error=>{pending.delete(key);throw error;}));
  return pending.get(key);
}
export function textFont(bold=false,fontId=defaultFontId){const font=loaded.get(fontKey(bold,fontId));if(!font)throw new Error('フォントの準備が完了していません。');return font;}
export function textWidth(value,item){const font=textFont(item.bold,item.fontId).parsed;return Array.from(value).reduce((sum,char)=>sum+font.glyphForCodePoint(char.codePointAt(0)).advanceWidth,0)*item.fontSize/font.unitsPerEm;}
export function textAscent(item){const font=textFont(item.bold,item.fontId).parsed;return font.ascent*item.fontSize/font.unitsPerEm;}
export function textDescent(item){const font=textFont(item.bold,item.fontId).parsed;return -font.descent*item.fontSize/font.unitsPerEm;}
export function validateText(value,bold,fontId=defaultFontId){
  if(value.length>10000)throw new Error('テキストは10,000文字以下にしてください。');
  const font=textFont(bold,fontId).parsed;
  const missing=[...new Set(Array.from(value).filter(char=>!['\n','\r','\t'].includes(char)&&!font.hasGlyphForCodePoint(char.codePointAt(0))))];
  if(missing.length)throw new Error('このフォントで表示できない文字があります: '+missing.slice(0,10).join(' '));
}
