import {readFile,writeFile} from 'node:fs/promises';

import {fontCatalog} from '../js/fonts.js';

// Keep the original binaries and OFL license alongside reproducible embedded data.
for(const font of fontCatalog)for(const weight of ['Regular','Bold']) {
  const source=new URL(`../vendor/fonts/${font.file}-${weight}.${font.extension}`,import.meta.url);
  const encoded=(await readFile(source)).toString('base64');
  await writeFile(new URL(`../vendor/fonts/${font.file}-${weight}.base64.js`,import.meta.url),
    `// ${font.file} — SIL OFL 1.1; see ${font.id==='noto-sans'?'LICENSE.txt':font.file+'-LICENSE.txt'}. Generated by scripts/embed-fonts.mjs.\nexport default "`+encoded+'";\n');
}
